Add Go proto build rule for p4runtime
p4lang/p4runtime pull request #359
Opened 2021-07-01 00:40 UTC by akarshgupta25

This PR adds go_proto_library rule for p4runtime.proto in BUILD file.

2021-07-01 00:41 UTC, smolkaj approved these changes
LGTM.

2021-07-01 00:43 UTC, smolkaj commented
@antoninbas, could you take a look?
I believe this should be an uncontroversial change that is just adding a missing BUILD target.

2021-07-01 00:44 UTC, antoninbas approved these changes

2021-07-01 00:44 UTC, antoninbas commented
@akarshgupta25 the Github workflow which checks the bazel build is failing

2021-07-01 00:44 UTC, smolkaj requested changes

2021-07-01 00:44 UTC, smolkaj commented on proto/BUILD.bazel
> +    protos = [":p4runtime_proto"],
The build is currently failing. I believe we have two include some additional dependencies here:

```
compilepkg: missing strict dependencies:
	/home/runner/.cache/bazel/_bazel_runner/1fc64d2e702c0d08ecdb88fe41750bb3/sandbox/linux-sandbox/2/execroot/com_github_p4lang_p4runtime/bazel-out/k8-fastbuild/bin/p4runtime_go_proto_/github.com/p4lang/p4runtime/go/p4/v1/p4runtime.pb.go: import of "github.com/p4lang/p4runtime/go/p4/config/v1"
	/home/runner/.cache/bazel/_bazel_runner/1fc64d2e702c0d08ecdb88fe41750bb3/sandbox/linux-sandbox/2/execroot/com_github_p4lang_p4runtime/bazel-out/k8-fastbuild/bin/p4runtime_go_proto_/github.com/p4lang/p4runtime/go/p4/v1/p4runtime.pb.go: import of "google.golang.org/genproto/googleapis/rpc/status"
No dependencies were provided.
```

2021-07-01 05:12 UTC, akarshgupta25 commented
I am unable to trigger a rebuild on Travis CI.
@antoninbas is there a way I can trigger the build to verify the new changes?

2021-07-02 02:01 UTC, smolkaj approved these changes
Thanks for getting things to build! LGTM.

2021-07-02 02:02 UTC, smolkaj commented
@antoninbas I believe this is ready to be merged?

2021-07-02 02:10 UTC, merged

2021-07-02 02:24 UTC, smolkaj commented
That was fast, thank you! :)